"""updated live table

Revision ID: 5b55bad784d3
Revises: e078c3035c71
Create Date: 2018-05-13 03:42:19.787866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b55bad784d3'
down_revision = 'e078c3035c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('live_ibfk_1', 'live', type_='foreignkey')
    op.create_foreign_key(None, 'live', 'user', ['user_id'], ['username'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'live', type_='foreignkey')
    op.create_foreign_key('live_ibfk_1', 'live', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
